spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: aws
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://egemonydatabase.codpa0uddgdm.ap-northeast-2.rds.amazonaws.com:3306/egemony?characterEncoding=UTF-8
    username: minsoo1430
    password: alfogkd0926
  devtools:
    livereload:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      show_sql : true
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: springboot-shop1-redis-001.9whkbr.0001.apn2.cache.amazonaws.com
    port: 6379

logging:
  level:
    org:
      springframework : INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error

cloud:
  aws:
    s3:
      bucket: egemony-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
    instanceProfile: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop1?characterEncoding=UTF-8
    username: root
    password: dltkdgudgksgywn0926*
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework : INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error