spring:
  profiles:
    active: aws

---

spring:
  profiles: aws
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://egemonydatabase.codpa0uddgdm.ap-northeast-2.rds.amazonaws.com:3306/egemony?characterEncoding=UTF-8
    username: minsoo1430
    password: alfogkd0926
  devtools:
    livereload:
      enabled: true
  freemaker:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: springboot-shop1-redis-001.9whkbr.0001.apn2.cache.amazonaws.com
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop1?characterEncoding=UTF-8
    username: root
    password: dltkdgudgksgywn0926*
